openapi: 3.0.3
info:
  title: Backend API
  version: 1.0.0
paths:
  /blogs:
    get:
      summary: Get all blog entries
  /hello:
    get:
      summary: Hello World Request
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: "Hello, World!"
